---
services:
  gateway:
    build:
      context: ./nerucci_gateway
      dockerfile: Dockerfile
      target: dev
    ports: [8080:8080]
    env_file: [./nerucci_gateway/.env]
    volumes: [./nerucci_gateway:/app]
  orders:
    build:
      context: ./nerucci_order
      dockerfile: Dockerfile
      target: dev
    ports: [2000:2000]
    env_file: [./nerucci_order/.env]
    volumes: [./nerucci_order:/app]
