---
services:
  gateway:
    build:
      context: ./nerucci_gateway
      dockerfile: Dockerfile
      target: dev
    ports: [8080:8080]
    expose:
      - 8080
    env_file: [./nerucci_gateway/.env]
    environment:
      - HTTP_ADDR=0.0.0.0:8080
      - GRPC_ADDR=orders:2000
    volumes: [./nerucci_gateway:/app]
  orders:
    build:
      context: ./nerucci_order
      dockerfile: Dockerfile
      target: dev
    ports: [2000:2000]
    env_file: [./nerucci_order/.env]
    environment:
      - GRPC_ADDR=0.0.0.0:2000
    volumes: [./nerucci_order:/app]
